// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classes.sql

package dbgen

import (
	"context"
	"database/sql"
)

const getClass = `-- name: GetClass :one
SELECT id, name, subject, written_weight, oral_weight, created_at, updated_at, deleted_at FROM classes WHERE id=? AND deleted_at IS NULL
`

func (q *Queries) GetClass(ctx context.Context, id int64) (Class, error) {
	row := q.db.QueryRowContext(ctx, getClass, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subject,
		&i.WrittenWeight,
		&i.OralWeight,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAssessments = `-- name: ListAssessments :many
SELECT id, class_id, name, type, date, weight, created_at, updated_at, deleted_at FROM assessments WHERE class_id=? AND deleted_at IS NULL ORDER BY date,id
`

func (q *Queries) ListAssessments(ctx context.Context, classID int64) ([]Assessment, error) {
	rows, err := q.db.QueryContext(ctx, listAssessments, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assessment
	for rows.Next() {
		var i Assessment
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.Name,
			&i.Type,
			&i.Date,
			&i.Weight,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClasses = `-- name: ListClasses :many
SELECT id, name, subject, written_weight, oral_weight, created_at, updated_at, deleted_at FROM classes WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, listClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Subject,
			&i.WrittenWeight,
			&i.OralWeight,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many
SELECT id, class_id, first_name, last_name, sort_order, created_at, updated_at, deleted_at FROM students WHERE class_id=? AND deleted_at IS NULL ORDER BY sort_order,last_name,first_name
`

func (q *Queries) ListStudents(ctx context.Context, classID int64) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, listStudents, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.FirstName,
			&i.LastName,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGrade = `-- name: UpsertGrade :exec
INSERT INTO grades(assessment_id,student_id,points,status) VALUES(?,?,?,'grade') ON CONFLICT(assessment_id,student_id) DO UPDATE SET points=excluded.points,status='grade',updated_at=CURRENT_TIMESTAMP
`

type UpsertGradeParams struct {
	AssessmentID int64
	StudentID    int64
	Points       sql.NullInt64
}

func (q *Queries) UpsertGrade(ctx context.Context, arg UpsertGradeParams) error {
	_, err := q.db.ExecContext(ctx, upsertGrade, arg.AssessmentID, arg.StudentID, arg.Points)
	return err
}
