// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package dbgen

import (
	"context"
	"database/sql"
)

const getAuditChange = `-- name: GetAuditChange :one
SELECT id, entity_type, entity_id, assessment_id, student_id, "action", before_json, after_json, undone_at, created_at FROM audit_log WHERE id = ?
`

func (q *Queries) GetAuditChange(ctx context.Context, id int64) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, getAuditChange, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.AssessmentID,
		&i.StudentID,
		&i.Action,
		&i.BeforeJson,
		&i.AfterJson,
		&i.UndoneAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditForEntity = `-- name: ListAuditForEntity :many
SELECT id, entity_type, entity_id, assessment_id, student_id, "action", before_json, after_json, undone_at, created_at FROM audit_log WHERE entity_type = ? AND entity_id = ? ORDER BY id DESC LIMIT ?
`

type ListAuditForEntityParams struct {
	EntityType string
	EntityID   int64
	Limit      int64
}

func (q *Queries) ListAuditForEntity(ctx context.Context, arg ListAuditForEntityParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditForEntity, arg.EntityType, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.AssessmentID,
			&i.StudentID,
			&i.Action,
			&i.BeforeJson,
			&i.AfterJson,
			&i.UndoneAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditForGrade = `-- name: ListAuditForGrade :many
SELECT id, entity_type, entity_id, assessment_id, student_id, "action", before_json, after_json, undone_at, created_at FROM audit_log WHERE entity_type = 'grade' AND assessment_id = ? AND student_id = ? ORDER BY id DESC LIMIT ?
`

type ListAuditForGradeParams struct {
	AssessmentID sql.NullInt64
	StudentID    sql.NullInt64
	Limit        int64
}

func (q *Queries) ListAuditForGrade(ctx context.Context, arg ListAuditForGradeParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditForGrade, arg.AssessmentID, arg.StudentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.AssessmentID,
			&i.StudentID,
			&i.Action,
			&i.BeforeJson,
			&i.AfterJson,
			&i.UndoneAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedAssessments = `-- name: ListDeletedAssessments :many
SELECT id, class_id, name, type, date, weight, created_at, updated_at, deleted_at FROM assessments WHERE deleted_at IS NOT NULL ORDER BY deleted_at DESC
`

func (q *Queries) ListDeletedAssessments(ctx context.Context) ([]Assessment, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedAssessments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assessment
	for rows.Next() {
		var i Assessment
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.Name,
			&i.Type,
			&i.Date,
			&i.Weight,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedClasses = `-- name: ListDeletedClasses :many
SELECT id, name, subject, written_weight, oral_weight, created_at, updated_at, deleted_at FROM classes WHERE deleted_at IS NOT NULL ORDER BY deleted_at DESC
`

func (q *Queries) ListDeletedClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Subject,
			&i.WrittenWeight,
			&i.OralWeight,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedStudents = `-- name: ListDeletedStudents :many
SELECT id, class_id, first_name, last_name, sort_order, created_at, updated_at, deleted_at FROM students WHERE deleted_at IS NOT NULL ORDER BY deleted_at DESC
`

func (q *Queries) ListDeletedStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.FirstName,
			&i.LastName,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
