// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
)

type Assessment struct {
	ID        int64
	ClassID   int64
	Name      string
	Type      string
	Date      string
	Weight    float64
	CreatedAt string
	UpdatedAt string
	DeletedAt sql.NullString
}

type AuditLog struct {
	ID           int64
	EntityType   string
	EntityID     int64
	AssessmentID sql.NullInt64
	StudentID    sql.NullInt64
	Action       string
	BeforeJson   string
	AfterJson    string
	UndoneAt     sql.NullString
	CreatedAt    string
}

type Class struct {
	ID            int64
	Name          string
	Subject       string
	WrittenWeight float64
	OralWeight    float64
	CreatedAt     string
	UpdatedAt     string
	DeletedAt     sql.NullString
}

type Grade struct {
	ID           int64
	AssessmentID int64
	StudentID    int64
	Points       sql.NullInt64
	Status       string
	CreatedAt    string
	UpdatedAt    string
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type Student struct {
	ID        int64
	ClassID   int64
	FirstName string
	LastName  string
	SortOrder int64
	CreatedAt string
	UpdatedAt string
	DeletedAt sql.NullString
}
